"""adicionando nova tabela

Revision ID: 734fa82d2e7f
Revises: d6583bffb154
Create Date: 2024-09-16 21:00:41.324933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734fa82d2e7f'
down_revision = 'd6583bffb154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('disc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocors')
    # ### end Alembic commands ###
